'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { initialState, type ClassName, type Event, type GameState } from '@/lib/engine';

type Reply = { narrative: string; needsRoll: boolean; rollSkill: string | null; rollDifficulty: number | null; scene: string; state: GameState; mode: 'ai' | 'demo'; aiError?: string };
type Stored = { campaigns: GameState[]; active?: string };
const key = 'infinita-campaigns-v2'; const classes: ClassName[] = ['Guerreiro', 'Explorador', 'Ladino', 'Místico'];

export default function Game() {
  const [campaigns, setCampaigns] = useState<GameState[]>([]); const [active, setActive] = useState<string>(); const [loaded, setLoaded] = useState(false);
  const [name, setName] = useState(''); const [campaignName, setCampaignName] = useState(''); const [className, setClassName] = useState<ClassName>('Explorador');
  const [text, setText] = useState(''); const [story, setStory] = useState(''); const [needsRoll, setNeedsRoll] = useState(false); const [rollSkill, setRollSkill] = useState(''); const [rollCd, setRollCd] = useState(12); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [menu, setMenu] = useState(true);
  const [sceneDisplay, setSceneDisplay] = useState<string>();
  const current = useMemo(() => campaigns.find(c => c.campaignId === active), [campaigns, active]);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(key) || 'null') as Stored | null; if (saved?.campaigns?.length) { setCampaigns(saved.campaigns); setActive(saved.active || saved.campaigns[0].campaignId); setMenu(false); } } finally { setLoaded(true); } }, []);
  useEffect(() => { if (loaded && campaigns.length) { try { localStorage.setItem(key, JSON.stringify({ campaigns: campaigns.map(({ sceneImage, ...campaign }) => campaign), active })); } catch { setNotice('A imagem da cena não foi salva, mas a campanha continua ativa.'); } } }, [campaigns, active, loaded]);
  useEffect(() => { if (current && !story) setStory(current.log.at(-1) || 'O que você faz?'); }, [current, story]);
  useEffect(() => {
    if (!current?.sceneImage) { setSceneDisplay(undefined); return; }
    const image = new Image(); image.onload = () => {
      try {
        const canvas = document.createElement('canvas'); canvas.width = 192; canvas.height = 108;
        const context = canvas.getContext('2d'); if (!context) return;
        context.imageSmoothingEnabled = false; context.drawImage(image, 0, 0, canvas.width, canvas.height);
        const pixels = context.getImageData(0, 0, canvas.width, canvas.height); const data = pixels.data;
        for (let i = 0; i < data.length; i += 4) { data[i] = Math.round(data[i] / 51) * 51; data[i + 1] = Math.round(data[i + 1] / 51) * 51; data[i + 2] = Math.round(data[i + 2] / 51) * 51; }
        context.putImageData(pixels, 0, 0); setSceneDisplay(canvas.toDataURL('image/png'));
      } catch { setSceneDisplay(current.sceneImage); }
    }; image.onerror = () => setSceneDisplay(current.sceneImage); image.src = current.sceneImage;
  }, [current?.sceneImage]);
  function update(next: GameState) { setCampaigns(all => all.map(c => c.campaignId === next.campaignId ? next : c)); }
  function outboundState(state: GameState) { const { sceneImage: _sceneImage, ...rest } = state; return rest; }
  function start(e: FormEvent) { e.preventDefault(); if (!name.trim() || !campaignName.trim()) return; const next = initialState(name.trim(), campaignName.trim(), className); setCampaigns(all => [...all, next]); setActive(next.campaignId); setStory(next.log[0]); setNotice('Campanha criada. Suas perícias escondidas serão reveladas pela prática.'); setMenu(false); }
  async function play(action: string) { if (!action.trim() || busy || !current) return; setBusy(true); setText(''); setNotice(''); try { const response = await fetch('/api/turn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, state: outboundState(current) }) }); const data: Reply = await response.json(); if (!response.ok) throw new Error(data as unknown as string); update({ ...data.state, sceneImage: data.state.sceneImage || current.sceneImage }); setStory(data.narrative); setNeedsRoll(data.needsRoll); setRollSkill(data.rollSkill || 'Perícia'); setRollCd(data.rollDifficulty || 12); if (data.mode === 'demo') setNotice(`Modo demo: ${data.aiError || 'a IA não respondeu.'}`); } catch { setNotice('Não foi possível registrar essa ação. Tente novamente.'); } finally { setBusy(false); } }
  function submit(e: FormEvent) { e.preventDefault(); play(text); }
  async function roll() { if (!current || busy) return; const die = Math.floor(Math.random() * 20) + 1; const bonus = Math.max(0, (current.skills[rollSkill]?.level || 1) - 1); const total = die + bonus; const outcome = total >= rollCd ? 'SUCESSO' : 'FALHA'; const event: Event = { kind: 'roll', text: `${rollSkill}: d20 (${die}) + ${bonus} = ${total} contra CD ${rollCd}. ${outcome}.` }; const withRoll = { ...current, events: [event, ...current.events].slice(0, 12), log: [...current.log, event.text] }; update(withRoll); setNeedsRoll(false); setBusy(true); setStory(`${event.text} O Mestre está resolvendo a consequência...`); try { const response = await fetch('/api/turn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: `Resolver o teste de ${rollSkill}`, state: outboundState(withRoll), roll: { skill: rollSkill, die, bonus, total, difficulty: rollCd } }) }); const data: Reply = await response.json(); if (!response.ok) throw new Error('Falha na resolução'); update({ ...data.state, sceneImage: data.state.sceneImage || withRoll.sceneImage }); setStory(data.narrative); setNeedsRoll(data.needsRoll); setRollSkill(data.rollSkill || 'Perícia'); setRollCd(data.rollDifficulty || 12); if (data.mode === 'demo') setNotice(`Modo demo: ${data.aiError || 'a IA não respondeu.'}`); } catch { setStory(`${event.text} O eco do resultado se perde por um instante. Tente continuar sua ação.`); } finally { setBusy(false); } }
  if (!loaded) return null;
  if (menu || !current) return <main><div className="setup"><div className="brand"><i className="rune"/><span>INFINITA</span></div><p>Uma campanha infinita: o mundo lembra cada escolha.</p>{campaigns.length > 0 && <div className="campaign-list"><b>CONTINUAR CAMPANHA</b>{campaigns.map(c => <button key={c.campaignId} type="button" onClick={() => { setActive(c.campaignId); setStory(c.log.at(-1) || 'O que você faz?'); setMenu(false); }}>{c.campaignName} · {c.characterName}</button>)}</div>}<form onSubmit={start}><label>NOME DO PERSONAGEM</label><input value={name} onChange={e => setName(e.target.value)} placeholder="Ex.: Lyra" maxLength={20}/><label>NOME DA CAMPANHA</label><input value={campaignName} onChange={e => setCampaignName(e.target.value)} placeholder="Ex.: As Cinzas de Valedouro" maxLength={32}/><label>CLASSE</label><input list="classes" value={className} onChange={e => setClassName(e.target.value)} placeholder="Ex.: Pistoleiro, Druida..." maxLength={24}/><datalist id="classes">{classes.map(c => <option key={c} value={c}/>)}</datalist><button className="start" type="submit">COMEÇAR CAMPANHA</button></form></div></main>;
  const visualClass = current.className.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  return <main><div className="console-label">● INFINITA COLOR</div><div className="shell"><header><div className="logo"><i className="rune"/><span>INFINITA</span></div><small>{current.campaignName.toUpperCase()} · NÍVEL {current.level} · D{current.day} · {String(current.hour).padStart(2, '0')}:00</small></header><div className="grid"><section className="adventure"><div className={`scene ${current.sceneImage ? 'generated' : ''}`}>{current.sceneImage ? <img className="scene-image" style={{ imageRendering: 'pixelated' }} src={sceneDisplay || current.sceneImage} alt={`Cena em ${current.location}`} /> : <><div className={`idle-avatar ${visualClass}`} aria-label={`Avatar de ${current.className}`}><i /></div><div className="moon"/><div className="mountains"/><div className="ground"/></>}<div className="scene-name">{current.location}</div></div><article className="narrative">{story}</article>{notice && <p className="notice">{notice}</p>}</section><aside><button className="switch" onClick={() => setMenu(true)}>≡ CAMPANHAS</button><h2>{current.characterName.toUpperCase()}</h2><p className="class-label">{current.className} · Nível {current.level}</p><div className="stat"><span>VITALIDADE</span><b>{current.hp}/{current.maxHp}</b></div><div className="bar"><i style={{ width: `${current.hp / current.maxHp * 100}%` }}/></div><div className="stat"><span>EXPERIÊNCIA</span><b>{current.xp}/{current.xpToNext}</b></div><div className="bar xpbar"><i style={{ width: `${current.xp / current.xpToNext * 100}%` }}/></div><div className="stat"><span>MOEDAS</span><b>{current.gold} G</b></div><hr/><h3>MOCHILA</h3><ul>{current.inventory.map(item => <li key={item}>› {item}</li>)}</ul><hr/><h3>PERÍCIAS DESCOBERTAS</h3><ul className="skills">{Object.entries(current.skills).filter(([, s]) => s.xp > 0).sort((a,b) => b[1].xp-a[1].xp).slice(0,5).map(([n,s]) => <li key={n}>› {n} Nv.{s.level} <em>+{s.xp} XP{s.trained ? ' ✦' : ''}</em></li>)}</ul><hr/><h3>REPUTAÇÃO</h3><p className="rep">Mundo {current.reputation.global} · Local {current.reputation.local}<br/>Região {current.reputation.regional}</p></aside></div><section className="events"><h3>REGISTRO DE CONSEQUÊNCIAS</h3>{current.events.length ? current.events.slice(0,4).map((e,i) => <p key={`${e.text}-${i}`} className={`event ${e.kind}`}>{e.text}</p>) : <p>Suas ações, ganhos, moral e títulos aparecerão aqui.</p>}</section><form onSubmit={submit}><label htmlFor="action">O QUE VOCÊ FAZ?</label>{needsRoll ? <button type="button" className="roll-only" onClick={roll} disabled={busy}><span>⚄</span> ROLAR D20 · {rollSkill} · CD {rollCd}</button> : <div className="input-row"><input id="action" value={text} onChange={e => setText(e.target.value)} placeholder="Escreva qualquer ação..." autoComplete="off" disabled={busy}/><button type="submit" disabled={busy}>{busy ? '...' : 'ENVIAR'}</button></div>}</form><footer>MEMÓRIA DA CAMPANHA ATIVA <span>●</span></footer></div></main>;
}
