'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import ProceduralScene from '@/components/ProceduralScene';
import { advanceDemo, initialState, type ClassName, type Event, type GameState } from '@/lib/engine';

type Reply = { narrative:string; needsRoll:boolean; rollSkill:string|null; rollDifficulty:number|null; state:GameState };
type Stored = { campaigns:GameState[]; active?:string }; const key='infinita-campaigns-v3'; const classes=['Guerreiro','Explorador','Ladino','Místico'];

export default function Game(){
 const [campaigns,setCampaigns]=useState<GameState[]>([]),[active,setActive]=useState<string>(),[loaded,setLoaded]=useState(false),[menu,setMenu]=useState(true);
 const [name,setName]=useState(''),[campaignName,setCampaignName]=useState(''),[className,setClassName]=useState<ClassName>('Explorador'),[text,setText]=useState(''),[story,setStory]=useState(''),[needsRoll,setNeedsRoll]=useState(false),[rollSkill,setRollSkill]=useState(''),[rollCd,setRollCd]=useState(12),[busy,setBusy]=useState(false);
 const current=useMemo(()=>campaigns.find(c=>c.campaignId===active),[campaigns,active]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null') as Stored|null;if(saved?.campaigns?.length){setCampaigns(saved.campaigns.map(({sceneImage,...c})=>c));setActive(saved.active||saved.campaigns[0].campaignId);setMenu(false)}}finally{setLoaded(true)}},[]);
 useEffect(()=>{if(loaded&&campaigns.length)localStorage.setItem(key,JSON.stringify({campaigns:campaigns.map(({sceneImage,...c})=>c),active}))},[campaigns,active,loaded]);
 useEffect(()=>{if(current&&!story)setStory(current.log.at(-1)||'O que você faz?')},[current,story]);
 const update=(next:GameState)=>setCampaigns(all=>all.map(c=>c.campaignId===next.campaignId?next:c));
 const start=(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!campaignName.trim())return;const next=initialState(name.trim(),campaignName.trim(),className);setCampaigns(all=>[...all,next]);setActive(next.campaignId);setStory(next.log[0]);setMenu(false)};
 async function turn(action:string){if(!current||busy)return;setBusy(true);try{const data=advanceDemo(current,action);update(data.state);setStory(data.narrative);setNeedsRoll(data.needsRoll);setRollSkill(data.rollSkill||'Perícia');setRollCd(data.rollDifficulty||12)}finally{setBusy(false)}}
 const submit=(e:FormEvent)=>{e.preventDefault();if(text.trim()){const action=text;setText('');turn(action)}};
 const roll=()=>{if(!current)return;const die=Math.floor(Math.random()*20)+1,bonus=Math.max(0,(current.skills[rollSkill]?.level||1)-1),total=die+bonus,success=total>=rollCd;const event:Event={kind:'roll',text:`${rollSkill}: d20 (${die}) + ${bonus} = ${total} contra CD ${rollCd}. ${success?'SUCESSO.':'FALHA.'}`};const next={...current,events:[event,...current.events].slice(0,12),log:[...current.log,event.text]};update(next);setNeedsRoll(false);setStory(success?`O teste de ${rollSkill} dá certo. Uma nova oportunidade aparece diante de você. O que você faz?`:`O teste de ${rollSkill} falha. A situação se complica, mas ainda há saídas. O que você faz?`)};
 if(!loaded)return null;
 if(menu||!current)return <main><div className="setup"><div className="brand"><i className="rune"/><span>INFINITA</span></div><p>Uma campanha infinita: o mundo lembra cada escolha.</p>{campaigns.length>0&&<div className="campaign-list"><b>CONTINUAR CAMPANHA</b>{campaigns.map(c=><button key={c.campaignId} onClick={()=>{setActive(c.campaignId);setStory(c.log.at(-1)||'O que você faz?');setMenu(false)}}>{c.campaignName} · {c.characterName}</button>)}</div>}<form onSubmit={start}><label>NOME DO PERSONAGEM</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Lyra"/><label>NOME DA CAMPANHA</label><input value={campaignName} onChange={e=>setCampaignName(e.target.value)} placeholder="Ex.: As Cinzas de Valedouro"/><label>CLASSE</label><input list="classes" value={className} onChange={e=>setClassName(e.target.value)} placeholder="Ex.: Druida, Pirata..."/><datalist id="classes">{classes.map(c=><option key={c} value={c}/>)}</datalist><button className="start">COMEÇAR CAMPANHA</button></form></div></main>;
 return <main><div className="console-label">● INFINITA COLOR</div><div className="shell"><header><div className="logo"><i className="rune"/><span>INFINITA</span></div><small>{current.campaignName.toUpperCase()} · NÍVEL {current.level} · D{current.day} · {String(current.hour).padStart(2,'0')}:00</small></header><div className="grid"><section className="adventure"><div className="scene generated"><ProceduralScene location={current.location} className={current.className} seed={current.campaignId}/><div className="scene-name">{current.location}</div></div><article className="narrative">{story}</article></section><aside><button className="switch" onClick={()=>setMenu(true)}>≡ CAMPANHAS</button><h2>{current.characterName.toUpperCase()}</h2><p className="class-label">{current.className} · Nível {current.level}</p><div className="stat"><span>VITALIDADE</span><b>{current.hp}/{current.maxHp}</b></div><div className="bar"><i style={{width:`${current.hp/current.maxHp*100}%`}}/></div><div className="stat"><span>EXPERIÊNCIA</span><b>{current.xp}/{current.xpToNext}</b></div><div className="bar xpbar"><i style={{width:`${current.xp/current.xpToNext*100}%`}}/></div><div className="stat"><span>MOEDAS</span><b>{current.gold} G</b></div><hr/><h3>MOCHILA</h3><ul>{current.inventory.map(i=><li key={i}>› {i}</li>)}</ul><hr/><h3>PERÍCIAS</h3><ul className="skills">{Object.entries(current.skills).filter(([,s])=>s.xp>0).slice(0,5).map(([n,s])=><li key={n}>› {n} Nv.{s.level}<em>+{s.xp} XP{s.trained?' ✦':''}</em></li>)}</ul><hr/><h3>REPUTAÇÃO</h3><p className="rep">Mundo {current.reputation.global} · Local {current.reputation.local}<br/>Região {current.reputation.regional}</p></aside></div><section className="events"><h3>REGISTRO DE CONSEQUÊNCIAS</h3>{current.events.length?current.events.slice(0,4).map((e,i)=><p key={`${e.text}-${i}`} className={`event ${e.kind}`}>{e.text}</p>):<p>Suas ações e ganhos aparecerão aqui.</p>}</section><form onSubmit={submit}><label>O QUE VOCÊ FAZ?</label>{needsRoll?<button type="button" className="roll-only" onClick={roll} disabled={busy}><span>⚄</span> ROLAR D20 · {rollSkill} · CD {rollCd}</button>:<div className="input-row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Escreva qualquer ação..." disabled={busy}/><button disabled={busy}>{busy?'...':'ENVIAR'}</button></div>}</form><footer><span>●</span></footer></div></main>;
}
